package test.andre.jberet.model;

import java.io.Serializable;
import java.sql.Timestamp;
import java.sql.Timestamp;
import java.sql.Timestamp;
import java.sql.Timestamp;

/**
 * JobExecution definition.
 * 
 * This file was generated by Ignite Web Console (12/14/2020, 09:58)
 **/
public class JobExecution implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for jobinstanceid. */
    private long jobinstanceid;

    /** Value for version. */
    private Integer version;

    /** Value for createtime. */
    private Timestamp createtime;

    /** Value for starttime. */
    private Timestamp starttime;

    /** Value for endtime. */
    private Timestamp endtime;

    /** Value for lastupdatedtime. */
    private Timestamp lastupdatedtime;

    /** Value for batchstatus. */
    private String batchstatus;

    /** Value for exitstatus. */
    private String exitstatus;

    /** Value for jobparameters. */
    private String jobparameters;

    /** Value for restartposition. */
    private String restartposition;

    /** Empty constructor. **/
    public JobExecution() {
        // No-op.
    }

    /** Full constructor. **/
    public JobExecution(long jobinstanceid,
        Integer version,
        Timestamp createtime,
        Timestamp starttime,
        Timestamp endtime,
        Timestamp lastupdatedtime,
        String batchstatus,
        String exitstatus,
        String jobparameters,
        String restartposition) {
        this.jobinstanceid = jobinstanceid;
        this.version = version;
        this.createtime = createtime;
        this.starttime = starttime;
        this.endtime = endtime;
        this.lastupdatedtime = lastupdatedtime;
        this.batchstatus = batchstatus;
        this.exitstatus = exitstatus;
        this.jobparameters = jobparameters;
        this.restartposition = restartposition;
    }

    /**
     * Gets jobinstanceid
     * 
     * @return Value for jobinstanceid.
     **/
    public long getJobinstanceid() {
        return jobinstanceid;
    }

    /**
     * Sets jobinstanceid
     * 
     * @param jobinstanceid New value for jobinstanceid.
     **/
    public void setJobinstanceid(long jobinstanceid) {
        this.jobinstanceid = jobinstanceid;
    }

    /**
     * Gets version
     * 
     * @return Value for version.
     **/
    public Integer getVersion() {
        return version;
    }

    /**
     * Sets version
     * 
     * @param version New value for version.
     **/
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * Gets createtime
     * 
     * @return Value for createtime.
     **/
    public Timestamp getCreatetime() {
        return createtime;
    }

    /**
     * Sets createtime
     * 
     * @param createtime New value for createtime.
     **/
    public void setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
    }

    /**
     * Gets starttime
     * 
     * @return Value for starttime.
     **/
    public Timestamp getStarttime() {
        return starttime;
    }

    /**
     * Sets starttime
     * 
     * @param starttime New value for starttime.
     **/
    public void setStarttime(Timestamp starttime) {
        this.starttime = starttime;
    }

    /**
     * Gets endtime
     * 
     * @return Value for endtime.
     **/
    public Timestamp getEndtime() {
        return endtime;
    }

    /**
     * Sets endtime
     * 
     * @param endtime New value for endtime.
     **/
    public void setEndtime(Timestamp endtime) {
        this.endtime = endtime;
    }

    /**
     * Gets lastupdatedtime
     * 
     * @return Value for lastupdatedtime.
     **/
    public Timestamp getLastupdatedtime() {
        return lastupdatedtime;
    }

    /**
     * Sets lastupdatedtime
     * 
     * @param lastupdatedtime New value for lastupdatedtime.
     **/
    public void setLastupdatedtime(Timestamp lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    /**
     * Gets batchstatus
     * 
     * @return Value for batchstatus.
     **/
    public String getBatchstatus() {
        return batchstatus;
    }

    /**
     * Sets batchstatus
     * 
     * @param batchstatus New value for batchstatus.
     **/
    public void setBatchstatus(String batchstatus) {
        this.batchstatus = batchstatus;
    }

    /**
     * Gets exitstatus
     * 
     * @return Value for exitstatus.
     **/
    public String getExitstatus() {
        return exitstatus;
    }

    /**
     * Sets exitstatus
     * 
     * @param exitstatus New value for exitstatus.
     **/
    public void setExitstatus(String exitstatus) {
        this.exitstatus = exitstatus;
    }

    /**
     * Gets jobparameters
     * 
     * @return Value for jobparameters.
     **/
    public String getJobparameters() {
        return jobparameters;
    }

    /**
     * Sets jobparameters
     * 
     * @param jobparameters New value for jobparameters.
     **/
    public void setJobparameters(String jobparameters) {
        this.jobparameters = jobparameters;
    }

    /**
     * Gets restartposition
     * 
     * @return Value for restartposition.
     **/
    public String getRestartposition() {
        return restartposition;
    }

    /**
     * Sets restartposition
     * 
     * @param restartposition New value for restartposition.
     **/
    public void setRestartposition(String restartposition) {
        this.restartposition = restartposition;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof JobExecution))
            return false;
        
        JobExecution that = (JobExecution)o;

        if (jobinstanceid != that.jobinstanceid)
            return false;
        

        if (version != null ? !version.equals(that.version) : that.version != null)
            return false;
        

        if (createtime != null ? !createtime.equals(that.createtime) : that.createtime != null)
            return false;
        

        if (starttime != null ? !starttime.equals(that.starttime) : that.starttime != null)
            return false;
        

        if (endtime != null ? !endtime.equals(that.endtime) : that.endtime != null)
            return false;
        

        if (lastupdatedtime != null ? !lastupdatedtime.equals(that.lastupdatedtime) : that.lastupdatedtime != null)
            return false;
        

        if (batchstatus != null ? !batchstatus.equals(that.batchstatus) : that.batchstatus != null)
            return false;
        

        if (exitstatus != null ? !exitstatus.equals(that.exitstatus) : that.exitstatus != null)
            return false;
        

        if (jobparameters != null ? !jobparameters.equals(that.jobparameters) : that.jobparameters != null)
            return false;
        

        if (restartposition != null ? !restartposition.equals(that.restartposition) : that.restartposition != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = (int)(jobinstanceid ^ (jobinstanceid >>> 32));

        res = 31 * res + (version != null ? version.hashCode() : 0);

        res = 31 * res + (createtime != null ? createtime.hashCode() : 0);

        res = 31 * res + (starttime != null ? starttime.hashCode() : 0);

        res = 31 * res + (endtime != null ? endtime.hashCode() : 0);

        res = 31 * res + (lastupdatedtime != null ? lastupdatedtime.hashCode() : 0);

        res = 31 * res + (batchstatus != null ? batchstatus.hashCode() : 0);

        res = 31 * res + (exitstatus != null ? exitstatus.hashCode() : 0);

        res = 31 * res + (jobparameters != null ? jobparameters.hashCode() : 0);

        res = 31 * res + (restartposition != null ? restartposition.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "JobExecution [" + 
            "jobinstanceid=" + jobinstanceid + ", " + 
            "version=" + version + ", " + 
            "createtime=" + createtime + ", " + 
            "starttime=" + starttime + ", " + 
            "endtime=" + endtime + ", " + 
            "lastupdatedtime=" + lastupdatedtime + ", " + 
            "batchstatus=" + batchstatus + ", " + 
            "exitstatus=" + exitstatus + ", " + 
            "jobparameters=" + jobparameters + ", " + 
            "restartposition=" + restartposition +
        "]";
    }
}