package test.andre.jberet.model;

import java.io.Serializable;

/**
 * JobInstance definition.
 * 
 * This file was generated by Ignite Web Console (12/14/2020, 09:58)
 **/
public class JobInstance implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for version. */
    private Integer version;

    /** Value for jobname. */
    private String jobname;

    /** Value for applicationname. */
    private String applicationname;

    /** Empty constructor. **/
    public JobInstance() {
        // No-op.
    }

    /** Full constructor. **/
    public JobInstance(Integer version,
        String jobname,
        String applicationname) {
        this.version = version;
        this.jobname = jobname;
        this.applicationname = applicationname;
    }

    /**
     * Gets version
     * 
     * @return Value for version.
     **/
    public Integer getVersion() {
        return version;
    }

    /**
     * Sets version
     * 
     * @param version New value for version.
     **/
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * Gets jobname
     * 
     * @return Value for jobname.
     **/
    public String getJobname() {
        return jobname;
    }

    /**
     * Sets jobname
     * 
     * @param jobname New value for jobname.
     **/
    public void setJobname(String jobname) {
        this.jobname = jobname;
    }

    /**
     * Gets applicationname
     * 
     * @return Value for applicationname.
     **/
    public String getApplicationname() {
        return applicationname;
    }

    /**
     * Sets applicationname
     * 
     * @param applicationname New value for applicationname.
     **/
    public void setApplicationname(String applicationname) {
        this.applicationname = applicationname;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof JobInstance))
            return false;
        
        JobInstance that = (JobInstance)o;

        if (version != null ? !version.equals(that.version) : that.version != null)
            return false;
        

        if (jobname != null ? !jobname.equals(that.jobname) : that.jobname != null)
            return false;
        

        if (applicationname != null ? !applicationname.equals(that.applicationname) : that.applicationname != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = version != null ? version.hashCode() : 0;

        res = 31 * res + (jobname != null ? jobname.hashCode() : 0);

        res = 31 * res + (applicationname != null ? applicationname.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "JobInstance [" + 
            "version=" + version + ", " + 
            "jobname=" + jobname + ", " + 
            "applicationname=" + applicationname +
        "]";
    }
}