package test.andre.jberet.model;

import java.io.Serializable;

/**
 * PartitionExecutionKey definition.
 * 
 * This file was generated by Ignite Web Console (12/14/2020, 09:58)
 **/
public class PartitionExecutionKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for partitionexecutionid. */
    private int partitionexecutionid;

    /** Value for stepexecutionid. */
    private long stepexecutionid;

    /** Empty constructor. **/
    public PartitionExecutionKey() {
        // No-op.
    }

    /** Full constructor. **/
    public PartitionExecutionKey(int partitionexecutionid,
        long stepexecutionid) {
        this.partitionexecutionid = partitionexecutionid;
        this.stepexecutionid = stepexecutionid;
    }

    /**
     * Gets partitionexecutionid
     * 
     * @return Value for partitionexecutionid.
     **/
    public int getPartitionexecutionid() {
        return partitionexecutionid;
    }

    /**
     * Sets partitionexecutionid
     * 
     * @param partitionexecutionid New value for partitionexecutionid.
     **/
    public void setPartitionexecutionid(int partitionexecutionid) {
        this.partitionexecutionid = partitionexecutionid;
    }

    /**
     * Gets stepexecutionid
     * 
     * @return Value for stepexecutionid.
     **/
    public long getStepexecutionid() {
        return stepexecutionid;
    }

    /**
     * Sets stepexecutionid
     * 
     * @param stepexecutionid New value for stepexecutionid.
     **/
    public void setStepexecutionid(long stepexecutionid) {
        this.stepexecutionid = stepexecutionid;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof PartitionExecutionKey))
            return false;
        
        PartitionExecutionKey that = (PartitionExecutionKey)o;

        if (partitionexecutionid != that.partitionexecutionid)
            return false;
        

        if (stepexecutionid != that.stepexecutionid)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = partitionexecutionid;

        res = 31 * res + (int)(stepexecutionid ^ (stepexecutionid >>> 32));

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "PartitionExecutionKey [" + 
            "partitionexecutionid=" + partitionexecutionid + ", " + 
            "stepexecutionid=" + stepexecutionid +
        "]";
    }
}