package com.gmail.awiradarma.model;

import java.io.Serializable;
import java.sql.Date;

/**
 * Pets definition.
 * 
 * This file was generated by Ignite Web Console (12/08/2020, 21:25)
 **/
public class Pets implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for name. */
    private String name;

    /** Value for birthDate. */
    private Date birthDate;

    /** Value for typeId. */
    private long typeId;

    /** Value for ownerId. */
    private long ownerId;

    /** Empty constructor. **/
    public Pets() {
        // No-op.
    }

    /** Full constructor. **/
    public Pets(String name,
        Date birthDate,
        long typeId,
        long ownerId) {
        this.name = name;
        this.birthDate = birthDate;
        this.typeId = typeId;
        this.ownerId = ownerId;
    }

    /**
     * Gets name
     * 
     * @return Value for name.
     **/
    public String getName() {
        return name;
    }

    /**
     * Sets name
     * 
     * @param name New value for name.
     **/
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets birthDate
     * 
     * @return Value for birthDate.
     **/
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * Sets birthDate
     * 
     * @param birthDate New value for birthDate.
     **/
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * Gets typeId
     * 
     * @return Value for typeId.
     **/
    public long getTypeId() {
        return typeId;
    }

    /**
     * Sets typeId
     * 
     * @param typeId New value for typeId.
     **/
    public void setTypeId(long typeId) {
        this.typeId = typeId;
    }

    /**
     * Gets ownerId
     * 
     * @return Value for ownerId.
     **/
    public long getOwnerId() {
        return ownerId;
    }

    /**
     * Sets ownerId
     * 
     * @param ownerId New value for ownerId.
     **/
    public void setOwnerId(long ownerId) {
        this.ownerId = ownerId;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Pets))
            return false;
        
        Pets that = (Pets)o;

        if (name != null ? !name.equals(that.name) : that.name != null)
            return false;
        

        if (birthDate != null ? !birthDate.equals(that.birthDate) : that.birthDate != null)
            return false;
        

        if (typeId != that.typeId)
            return false;
        

        if (ownerId != that.ownerId)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = name != null ? name.hashCode() : 0;

        res = 31 * res + (birthDate != null ? birthDate.hashCode() : 0);

        res = 31 * res + (int)(typeId ^ (typeId >>> 32));

        res = 31 * res + (int)(ownerId ^ (ownerId >>> 32));

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Pets [" + 
            "name=" + name + ", " + 
            "birthDate=" + birthDate + ", " + 
            "typeId=" + typeId + ", " + 
            "ownerId=" + ownerId +
        "]";
    }
}