package com.gmail.awiradarma.model;

import java.io.Serializable;

/**
 * VetSpecialtiesKey definition.
 * 
 * This file was generated by Ignite Web Console (12/08/2020, 21:25)
 **/
public class VetSpecialtiesKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for vetId. */
    private long vetId;

    /** Value for specialtyId. */
    private long specialtyId;

    /** Empty constructor. **/
    public VetSpecialtiesKey() {
        // No-op.
    }

    /** Full constructor. **/
    public VetSpecialtiesKey(long vetId,
        long specialtyId) {
        this.vetId = vetId;
        this.specialtyId = specialtyId;
    }

    /**
     * Gets vetId
     * 
     * @return Value for vetId.
     **/
    public long getVetId() {
        return vetId;
    }

    /**
     * Sets vetId
     * 
     * @param vetId New value for vetId.
     **/
    public void setVetId(long vetId) {
        this.vetId = vetId;
    }

    /**
     * Gets specialtyId
     * 
     * @return Value for specialtyId.
     **/
    public long getSpecialtyId() {
        return specialtyId;
    }

    /**
     * Sets specialtyId
     * 
     * @param specialtyId New value for specialtyId.
     **/
    public void setSpecialtyId(long specialtyId) {
        this.specialtyId = specialtyId;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof VetSpecialtiesKey))
            return false;
        
        VetSpecialtiesKey that = (VetSpecialtiesKey)o;

        if (vetId != that.vetId)
            return false;
        

        if (specialtyId != that.specialtyId)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = (int)(vetId ^ (vetId >>> 32));

        res = 31 * res + (int)(specialtyId ^ (specialtyId >>> 32));

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "VetSpecialtiesKey [" + 
            "vetId=" + vetId + ", " + 
            "specialtyId=" + specialtyId +
        "]";
    }
}