package com.gmail.awiradarma.model;

import java.io.Serializable;

/**
 * Vets definition.
 * 
 * This file was generated by Ignite Web Console (12/08/2020, 21:25)
 **/
public class Vets implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for firstName. */
    private String firstName;

    /** Value for lastName. */
    private String lastName;

    /** Empty constructor. **/
    public Vets() {
        // No-op.
    }

    /** Full constructor. **/
    public Vets(String firstName,
        String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    /**
     * Gets firstName
     * 
     * @return Value for firstName.
     **/
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets firstName
     * 
     * @param firstName New value for firstName.
     **/
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Gets lastName
     * 
     * @return Value for lastName.
     **/
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets lastName
     * 
     * @param lastName New value for lastName.
     **/
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Vets))
            return false;
        
        Vets that = (Vets)o;

        if (firstName != null ? !firstName.equals(that.firstName) : that.firstName != null)
            return false;
        

        if (lastName != null ? !lastName.equals(that.lastName) : that.lastName != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = firstName != null ? firstName.hashCode() : 0;

        res = 31 * res + (lastName != null ? lastName.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Vets [" + 
            "firstName=" + firstName + ", " + 
            "lastName=" + lastName +
        "]";
    }
}