package startup;

import config.SQLFunction;
import config.ServerConfigurationFactory;

import java.util.ArrayList;

import org.apache.ignite.Ignite;
import org.apache.ignite.IgniteCache;
import org.apache.ignite.Ignition;
import org.apache.ignite.cache.query.SqlFieldsQuery;

/** This file was generated by Ignite Web Console (12/14/2020, 09:58) **/
public class ServerNodeCodeStartup {
    /**
     * Start up node with specified configuration.
     * 
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {
        long start=0;

        Ignite ignite = Ignition.start(ServerConfigurationFactory.createConfiguration());

        System.out.println(">>> Loading caches...");

        System.out.println(">>> Loading cache: JobExecutionCache");
        ignite.cache("JobExecutionCache").loadCache(null);
        start = getMaxSequence("JOBEXECUTIONID", "JOB_EXECUTION",ignite.cache("JobExecutionCache"));
        SQLFunction.createSequence(ignite,"JOBEXECUTIONID", start);

        System.out.println(">>> Loading cache: JobInstanceCache");
        ignite.cache("JobInstanceCache").loadCache(null);
        start = getMaxSequence("JOBINSTANCEID", "JOB_INSTANCE",ignite.cache("JobInstanceCache"));
        SQLFunction.createSequence(ignite,"JOBINSTANCEID", start);

        System.out.println(">>> Loading cache: PartitionExecutionCache");
        ignite.cache("PartitionExecutionCache").loadCache(null);

        System.out.println(">>> Loading cache: StepExecutionCache");
        ignite.cache("StepExecutionCache").loadCache(null);
        start = getMaxSequence("STEPEXECUTIONID", "STEP_EXECUTION",ignite.cache("StepExecutionCache"));
        SQLFunction.createSequence(ignite,"STEPEXECUTIONID", start);


        System.out.println(">>> All caches loaded!");


    }

    public static long getMaxSequence(String sequence_column_name, String tablename, IgniteCache cachename) {
        // Preparing the query that uses the custom defined 'sqr' function.
        SqlFieldsQuery query = new SqlFieldsQuery("SELECT max(" + sequence_column_name + ") FROM "+ tablename);

        // Executing the query.
        return  (long) ((ArrayList) cachename.query(query).getAll().get(0)).get(0);
    }
}